package controllers;

import controllers.gen.paginaFirmaMultiplesDocumentosControllerGen;

public class paginaFirmaMultiplesDocumentosController extends paginaFirmaMultiplesDocumentosControllerGen {

}
