language: java

jdk:
- oraclejdk7

python:
  - "3.3"

env:
  global:
    - PLAY_VERSION=1.2.4
    - FAPSDK=${TRAVIS_BUILD_DIR}
    - PLAY=${FAPSDK}/play-${PLAY_VERSION}/play
    - CASPERJS=${FAPSDK}/CasperJS

before_script:
- wget http://downloads.typesafe.com/releases/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip
- git clone git://github.com/n1k0/casperjs.git ${CASPERJS}

script:
- echo FAPSDK=${FAPSDK}
- cd fap
- ant -f compiler.xml
- cd ${FAPSDK}/fap
- ${PLAY} deps --sync -Dfapsdk=${FAPSDK} --clearcache > /dev/null
- python generate.py
- cd ${FAPSDK}/apps/test
- ${PLAY} dependencies  --sync -Dfapsdk=${FAPSDK} > /dev/null
- ${PLAY} fap:generate
- ${PLAY} auto-test -XX:MaxPermSize=1024m
- ${PLAY} test & casper_pid=$!
- sleep 30
- ${CASPERJS}/casperjs test `pwd`/test/CasperJS/*.test.js
- kill casper_pid

