language: java

jdk:
- oraclejdk7

env:
  global:
    - PLAY_VERSION=1.2.4
    - FAPSDK=${TRAVIS_BUILD_DIR}

before_script:
- wget http://downloads.typesafe.com/releases/play-${PLAY_VERSION}.zip
- unzip -q play-${PLAY_VERSION}.zip

script:
- echo FAPSDK=${FAPSDK}
- cd fap
- ant -f compiler.xml

script:
- cd ${FAPSDK}/fap
- ${FAPSDK}/play-${PLAY_VERSION}/play deps --sync -Dfapsdk=${FAPSDK} --clearcache
- python generate.py
