package controllers.popups;

import controllers.gen.popups.PopupDatosNuevaComunicacionInternaControllerGen;

public class PopupDatosNuevaComunicacionInternaController extends PopupDatosNuevaComunicacionInternaControllerGen {

}
