package controllers.popups;

import controllers.gen.popups.PopupDatosBorrarComunicacionInternaControllerGen;

public class PopupDatosBorrarComunicacionInternaController extends PopupDatosBorrarComunicacionInternaControllerGen {

}
