package controllers.popups;

import controllers.gen.popups.PopUpDocJustificacionPresentadosControllerGen;

public class PopUpDocJustificacionPresentadosController extends PopUpDocJustificacionPresentadosControllerGen {

}
