/*
 * generated by Xtext
 */
package es.fap.simpleled.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtext.documentation.IEObjectDocumentationProvider;
import org.eclipse.xtext.resource.containers.IAllContainersState;
import org.eclipse.xtext.ui.editor.hover.DispatchingEObjectTextHover;
import org.eclipse.xtext.ui.editor.hover.IEObjectHoverProvider;
import org.eclipse.xtext.ui.editor.syntaxcoloring.DefaultHighlightingConfiguration;
import org.eclipse.xtext.ui.editor.syntaxcoloring.ISemanticHighlightingCalculator;

import com.google.inject.Binder;
import com.google.inject.Provider;

import es.fap.simpleled.ui.coloring.FapSemanticHighlighting;
import es.fap.simpleled.ui.documentation.FapDocumentationProvider;
import es.fap.simpleled.ui.documentation.FapHoverProvider;

/**
 * Use this class to register components to be used within the IDE.
 */

public class LedUiModule extends es.fap.simpleled.ui.AbstractLedUiModule {
	
	public LedUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
	
//	public Provider<IAllContainersState> provideIAllContainersState() {
//		return org.eclipse.xtext.ui.shared.Access.getWorkspaceProjectsState();
//	}
	
	public Class<? extends DispatchingEObjectTextHover> bindDispatchingEObjectTextHover() {
		return FapHoverProvider.class;
	}
	
	public Class<? extends IEObjectDocumentationProvider> bindIEObjectDocumentationProvider() {
	    return FapDocumentationProvider.class;
	}
	
	public Class<? extends IEObjectHoverProvider> bindIEObjectHoverProvider() {
	    return FapDocumentationProvider.class;
	}
	
	public Class<? extends ISemanticHighlightingCalculator> bindISemanticHighlightingCalculator() {
	    return FapSemanticHighlighting.class;
	}
	
	public Class<? extends DefaultHighlightingConfiguration> bindDefaultHighlightingConfiguration() {
	    return FapSemanticHighlighting.class;
	}
	
	@Override
	public void configure(Binder binder){
		super.configure(binder);
	}
}
