package controllers;

import controllers.gen.AportarDocumentacionAceptacionRenunciaControllerGen;

public class AportarDocumentacionAceptacionRenunciaController extends AportarDocumentacionAceptacionRenunciaControllerGen {

}
