package controllers;

import controllers.gen.BorrarSolicitudTransmisionSVDIdentidadControllerGen;

public class BorrarSolicitudTransmisionSVDIdentidadController extends BorrarSolicitudTransmisionSVDIdentidadControllerGen {

}
