package controllers;

import controllers.gen.BorrarSolicitudTransmisionSVDResidenciaControllerGen;

public class BorrarSolicitudTransmisionSVDResidenciaController extends BorrarSolicitudTransmisionSVDResidenciaControllerGen {

}
