package controllers;

import controllers.gen.DocumentoConsultaPortafirmaCrearControllerGen;

public class DocumentoConsultaPortafirmaCrearController extends DocumentoConsultaPortafirmaCrearControllerGen {

}
