package controllers;

import controllers.gen.EditarCesionesDatosIdentidadSVDControllerGen;

public class EditarCesionesDatosIdentidadSVDController extends EditarCesionesDatosIdentidadSVDControllerGen {

}
