package controllers;

import controllers.gen.EditarCesionesDatosResidenciaExpedienteSVDControllerGen;

public class EditarCesionesDatosResidenciaExpedienteSVDController extends EditarCesionesDatosResidenciaExpedienteSVDControllerGen {

}
