package controllers;

import controllers.gen.EditarCesionesDatosResidenciaSVDControllerGen;

public class EditarCesionesDatosResidenciaSVDController extends EditarCesionesDatosResidenciaSVDControllerGen {

}
