package controllers;

import controllers.gen.EditarSolicitudTransmisionSVDResidenciaControllerGen;

public class EditarSolicitudTransmisionSVDResidenciaController extends EditarSolicitudTransmisionSVDResidenciaControllerGen {

}
