package controllers;

import controllers.gen.PaginaNuevaComunicacionInternaDocumentosControllerGen;

public class PaginaNuevaComunicacionInternaDocumentosController extends PaginaNuevaComunicacionInternaDocumentosControllerGen {

}
