package controllers;

import controllers.gen.PaginaDatosLeerComunicacionInternaControllerGen;

public class PaginaDatosLeerComunicacionInternaController extends PaginaDatosLeerComunicacionInternaControllerGen {

}
