package controllers;

import controllers.gen.PaginaDocumentoVerificacionLeerControllerGen;

public class PaginaDocumentoVerificacionLeerController extends PaginaDocumentoVerificacionLeerControllerGen {

}
