package controllers;

import controllers.gen.PaginaVerificacionesAnterioresControllerGen;

public class PaginaVerificacionesAnterioresController extends PaginaVerificacionesAnterioresControllerGen {

}
