package controllers;

import controllers.gen.PaginaDocumentoVerificacionLeerAnterioresControllerGen;

public class PaginaDocumentoVerificacionLeerAnterioresController extends PaginaDocumentoVerificacionLeerAnterioresControllerGen {

}
