package controllers;

import controllers.gen.VerCesionesDatosResidenciaExpedienteSVDControllerGen;

public class VerCesionesDatosResidenciaExpedienteSVDController extends VerCesionesDatosResidenciaExpedienteSVDControllerGen {

}
