package controllers.serviciosweb;

import controllers.gen.serviciosweb.WSAportacionesSinRegistroSWControllerGen;

public class WSAportacionesSinRegistroSWController extends WSAportacionesSinRegistroSWControllerGen {

}
