package controllers.popups;

import controllers.gen.popups.PopupPersonaSolicitantePersonaJuridicaJuridicaTablaControllerGen;

public class PopupPersonaSolicitantePersonaJuridicaJuridicaTablaController extends PopupPersonaSolicitantePersonaJuridicaJuridicaTablaControllerGen {

}
