package controllers.popups;

import controllers.gen.popups.PopupSolicitanteJurJuridicaTablaControllerGen;

public class PopupSolicitanteJurJuridicaTablaController extends PopupSolicitanteJurJuridicaTablaControllerGen {

}
