package controllers.popups;

import controllers.gen.popups.PopupPersonaSolicitante2JuridicaTablaControllerGen;

public class PopupPersonaSolicitante2JuridicaTablaController extends PopupPersonaSolicitante2JuridicaTablaControllerGen {

}
