/*
 * generated by Xtext
 */
package es.fap.simpleled;

import com.google.inject.Binder;

import es.fap.simpleled.led.util.ModelUtils;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class LedRuntimeModule extends es.fap.simpleled.AbstractLedRuntimeModule {
	
	@Override
	public void configure(Binder binder) {
		binder.requestStaticInjection(ModelUtils.class);
		super.configure(binder);
	}
	
}
