/*
 * generated by Xtext
 */
package es.fap.simpleled;

/**
 * Use this class to register components to be used at runtime / without the
 * Equinox extension registry.
 */
public class LedRuntimeModule extends es.fap.simpleled.AbstractLedRuntimeModule {
	
}
