/*
* generated by Xtext
*/
package es.fap.simpleled.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class LedOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
